@baseUrl = http://localhost:3000

### Obtener citas
GET {{baseUrl}}/api/citas

### Crear cita
POST {{baseUrl}}/api/citas
Content-Type: application/json

{
  "paciente_id": 1,
  "odontologo_id": 1,
  "sillon_id": 1,
  "fecha": "2026-05-01T10:00:00",
  "estado": "PENDIENTE",
  "subtotal": 100000
}

### Actualizar cita
PUT {{baseUrl}}/api/citas/1
Content-Type: application/json

{
  "estado": "CONFIRMADA",
  "subtotal": 150000
}

### Eliminar cita
DELETE {{baseUrl}}/api/citas/1